CREATE DATABASE CAFETERIA;
USE CAFETERIA;

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    REFERENCIA VARCHAR(100) NOT NULL,
    PRECIO INT NOT NULL,
    PESO INT NOT NULL,
    ID_CATEGORIA_FK INT NOT NULL,
    STOCK INT NOT NULL,
    FECHA_CREACION DATE NOT NULL,
    FOREIGN KEY(ID_CATEGORIA_FK) REFERENCES CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE ENCABEZADO_FACTURA(
	ID_ENCABEZADO_FACTURA INT NOT NULL PRIMARY KEY,
    FECHA_FACTURA DATE NOT NULL,
    TOTAL INT NOT NULL
);
CREATE TABLE DETALLE_FACTURA(
	ID_DETALLE_FACTURA INT NOT NULL,
    ID_ENCABEZADO_FACTURA_FK INT NOT NULL,
    ID_PRODUCTO_FK INT NOT NULL,
    CANTIDAD INT NOT NULL,
    SUBTOTAL INT NOT NULL,
    FOREIGN KEY(ID_ENCABEZADO_FACTURA_FK) REFERENCES ENCABEZADO_FACTURA (ID_ENCABEZADO_FACTURA),
    FOREIGN KEY(ID_PRODUCTO_FK) REFERENCES PRODUCTO (ID_PRODUCTO)
);