CREATE DATABASE CAFETERIA;
USE CAFETERIA;

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE VARCHAR(50) NOT NULL
);



CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    REFERENCIA VARCHAR(100) NOT NULL,
    PRECIO INT NOT NULL,
    PESO INT NOT NULL,
    ID_CATEGORIA_FK INT NOT NULL,
    STOCK INT NOT NULL,
    FECHA_CREACION DATE NOT NULL,
    FOREIGN KEY(ID_CATEGORIA_FK) REFERENCES CATEGORIA (ID_CATEGORIA)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE VENTAS(
	ID_VENTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FECHA_VENTA DATE NOT NULL,
    ID_PRODUCTO_FK INT NOT NULL,
    CANTIDAD INT NOT NULL,
    TOTAL INT NOT NULL,
    FOREIGN KEY(ID_PRODUCTO_FK) REFERENCES PRODUCTO (ID_PRODUCTO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

INSERT INTO CATEGORIA (NOMBRE) VALUES("Bebidas");
